# Build.ps1 — Concatenates helper functions into a single deployable .ps1
# Run from project root: pwsh -File Build.ps1

$ErrorActionPreference = 'Stop'

$projectRoot = $PSScriptRoot
$distDir = Join-Path $projectRoot 'dist'
$outputFile = Join-Path $distDir 'GPUpdateAndLogoff.ps1'

# Ensure dist/ exists
if (-not (Test-Path $distDir)) {
    New-Item -ItemType Directory -Path $distDir -Force | Out-Null
}

# Helper files in dependency order (Write-Log first — everything else calls it)
$helpers = @(
    'src/helpers/Write-Log.ps1'
    'src/helpers/Invoke-LogRotation.ps1'
    'src/helpers/Register-EventSource.ps1'
    'src/helpers/Set-Prerequisites.ps1'
    'src/helpers/Resolve-QuserPath.ps1'
    'src/helpers/Get-UserSessions.ps1'
    'src/helpers/Invoke-ForcedLogoff.ps1'
    'src/helpers/Invoke-MsgExe.ps1'
    'src/helpers/Invoke-GpUpdate.ps1'
    'src/helpers/Invoke-OvernightAction.ps1'
    'src/helpers/Invoke-LogoffTriggeredAction.ps1'
)

$sections = @()

# Param block — must appear before all function definitions in the output
$paramBlock = @'

param(
    [Parameter(Mandatory)]
    [ValidateSet('Overnight','LogoffTriggered')]
    [string]$Mode
)
'@

# Header
$timestamp = (Get-Date).ToString('yyyy-MM-ddTHH:mm:ss.fffzzz')
$header = @"
# GPUpdateAndLogoff.ps1
# Generated by Build.ps1 on $timestamp
# Source files: $($helpers -join ', ')
# DO NOT EDIT — modify source files in src/helpers/ and re-run Build.ps1
"@
$sections += $header
$sections += $paramBlock

# Concatenate helpers
foreach ($helper in $helpers) {
    $fullPath = Join-Path $projectRoot $helper
    if (-not (Test-Path $fullPath)) {
        throw "Helper file not found: $fullPath"
    }
    $sections += ""
    $sections += "#region $helper"
    $sections += (Get-Content -Path $fullPath -Raw).TrimEnd()
    $sections += "#endregion $helper"
}

# Main entry point scaffold (without param block)
$entryPoint = @'

#region Main Entry Point

# Fallback log path used by the catch handler if prerequisites have not yet set $script:LogPath
$script:LogPath = "C:\DatoLogs\GPUpdate\$env:COMPUTERNAME.log"

try {
    Register-EventSource -Source 'GPUpdateTask' -LogName 'Application'
    Write-Log -Message 'GPUpdateAndLogoff script started.' -Level INFO

    # Prerequisites — AllowRemoteRPC must be set before quser can enumerate sessions as SYSTEM
    if (-not (Set-AllowRemoteRpc)) { throw 'Set-AllowRemoteRpc failed' }
    if (-not (Enable-AuditLogoff)) { throw 'Enable-AuditLogoff failed' }

    # Snapshot logged-on users AFTER AllowRemoteRpc but BEFORE any logoff actions
    # Try multiple methods — quser (proven to work on this machine), WMI fallbacks
    $script:DetectedUsers = 'None'
    try {
        # Method 1: quser (requires AllowRemoteRPC from SYSTEM context)
        $qPath = if ($env:PROCESSOR_ARCHITEW6432 -eq 'AMD64') { "$env:SystemRoot\Sysnative\quser.exe" } else { "$env:SystemRoot\System32\quser.exe" }
        if (Test-Path $qPath) {
            $qOut = & $qPath 2>&1
            $qStr = $qOut -join "`n"
            if ($qStr -notmatch 'No User exists' -and $qOut -and ($qOut | Where-Object { $_.Trim() -ne '' }).Count -gt 1) {
                $names = ($qOut | Select-Object -Skip 1 | ForEach-Object {
                    ($_ -replace '^\s*>\s*','').Trim() -replace '\s{2,}.*', ''
                } | Where-Object { $_ -ne '' }) -join ', '
                if ($names) { $script:DetectedUsers = $names }
            }
        }
    } catch {}
    if ($script:DetectedUsers -eq 'None') {
        try {
            # Method 2: WMI explorer.exe process owner
            $explorerProcs = Get-CimInstance -ClassName Win32_Process -Filter "Name='explorer.exe'" -ErrorAction SilentlyContinue
            if ($explorerProcs) {
                $owners = @()
                foreach ($proc in @($explorerProcs)) {
                    $owner = Invoke-CimMethod -InputObject $proc -MethodName GetOwner -ErrorAction SilentlyContinue
                    if ($owner -and $owner.ReturnValue -eq 0 -and $owner.User) { $owners += $owner.User }
                }
                $unique = $owners | Select-Object -Unique | Sort-Object
                if ($unique) { $script:DetectedUsers = $unique -join ', ' }
            }
        } catch {}
    }
    if ($script:DetectedUsers -eq 'None') {
        try {
            # Method 3: Win32_ComputerSystem.UserName (console user)
            $cs = Get-CimInstance -ClassName Win32_ComputerSystem -ErrorAction SilentlyContinue
            if ($cs.UserName) { $script:DetectedUsers = $cs.UserName -replace '^.*\\', '' }
        } catch {}
    }
    if ($script:DetectedUsers -eq 'None') {
        try {
            # Method 4: Logoff 4647 event (System logs out user before script sees them during logoff trigger)
            $evt = Get-WinEvent -FilterHashtable @{LogName='Security'; ID=4647} -MaxEvents 1 -ErrorAction SilentlyContinue
            if ($evt -and ($evt.TimeCreated -gt (Get-Date).AddMinutes(-5))) {
                if ($evt.Properties.Count -gt 1 -and $evt.Properties[1].Value) {
                    $uName = $evt.Properties[1].Value
                    if ($uName -notmatch '\$') { # Ignore machine accounts
                        $script:DetectedUsers = $uName
                    }
                }
            }
        } catch {}
    }
    if ($script:DetectedUsers -eq 'None') {
        try {
            # Method 5: Loaded User Profiles in HKEY_USERS
            $hkuPaths = Get-ChildItem -Path Registry::HKEY_USERS -ErrorAction SilentlyContinue | Where-Object { $_.PSChildName -match '^S-1-5-21-\d+-\d+-\d+-\d+$' }
            if ($hkuPaths) {
                $loggedIn = @()
                foreach ($hku in $hkuPaths) {
                    try {
                        $sid = [System.Security.Principal.SecurityIdentifier]::new($hku.PSChildName)
                        $ntAccount = $sid.Translate([System.Security.Principal.NTAccount])
                        $username = $ntAccount.Value -replace '^.*\\', ''
                        if ($username -notmatch 'SYSTEM|LOCAL SERVICE|NETWORK SERVICE') {
                            $loggedIn += $username
                        }
                    } catch {}
                }
                if ($loggedIn.Count -gt 0) {
                    $unique = $loggedIn | Sort-Object -Unique
                    $script:DetectedUsers = $unique -join ', '
                }
            }
        } catch {}
    }
    if ($script:DetectedUsers -eq 'None') {
        try {
            # Method 6: Get-Process explorer.exe
            $explorers = Get-Process -Name explorer -IncludeUserName -ErrorAction SilentlyContinue
            if ($explorers) {
                $users = @()
                foreach ($e in $explorers) {
                    if ($e.UserName) {
                        $uName = $e.UserName -replace '^.*\\', ''
                        if ($uName -notmatch 'SYSTEM|LOCAL SERVICE|NETWORK SERVICE|DWM-') {
                            $users += $uName
                        }
                    }
                }
                if ($users.Count -gt 0) {
                    $unique = $users | Sort-Object -Unique
                    $script:DetectedUsers = $unique -join ', '
                }
            }
        } catch {}
    }
    Write-Log -Message "Detected users: $script:DetectedUsers" -Level INFO

    $script:NetworkLogPath = "\\HFA2\open\logs\GPUpdate\$env:COMPUTERNAME.log"

    # Ensure log directories exist
    $logDir = Split-Path $script:LogPath -Parent
    if (-not (Test-Path $logDir)) {
        New-Item -ItemType Directory -Path $logDir -Force | Out-Null
    }
    if ($script:NetworkLogPath) {
        $networkLogDir = Split-Path $script:NetworkLogPath -Parent
        try {
            if (-not (Test-Path $networkLogDir)) {
                New-Item -ItemType Directory -Path $networkLogDir -Force | Out-Null
            }
        } catch {}
    }

    # Overwrite log with header — pass pre-captured users
    Invoke-LogRotation -LogPath $script:LogPath -Users $script:DetectedUsers
    if ($script:NetworkLogPath) {
        Invoke-LogRotation -LogPath $script:NetworkLogPath -Users $script:DetectedUsers
    }

    $quserPath = Resolve-QuserPath
    if ($null -eq $quserPath) { throw 'Resolve-QuserPath failed' }

    Write-Log -Message 'All prerequisites satisfied.' -Level INFO

    # Dispatch to mode-specific orchestrator
    Write-Log -Message "Dispatching mode: $Mode" -Level INFO

    if ($Mode -eq 'Overnight') {
        Invoke-OvernightAction -QuserPath $quserPath
    } elseif ($Mode -eq 'LogoffTriggered') {
        Invoke-LogoffTriggeredAction -QuserPath $quserPath
    }

    exit 0
}
catch {
    Write-Log -Message "Script failed: $_" -Level ERROR
    exit 1001
}

#endregion Main Entry Point
'@
$sections += $entryPoint

# Write output
$output = $sections -join "`n"
Set-Content -Path $outputFile -Value $output -Encoding UTF8 -Force

Write-Host "Build complete: $outputFile"

# --- Phase 4: Build deployer.ps1 with embedded action script ---

$deployerSource = Join-Path $projectRoot 'src' 'deployer' 'deployer.ps1'
$deployerOutput = Join-Path $distDir 'deployer.ps1'

if (-not (Test-Path $outputFile)) {
    throw "GPUpdateAndLogoff.ps1 not found at $outputFile - action script must be built first"
}
if (-not (Test-Path $deployerSource)) {
    throw "Deployer source not found at $deployerSource"
}

$actionScriptContent = Get-Content -Path $outputFile -Raw
$deployerTemplate    = Get-Content -Path $deployerSource -Raw

# Verify action script content does not contain here-string terminator
if ($actionScriptContent -match "(?m)^'@") {
    throw "Action script contains line-start '@ which would break here-string embedding"
}

# Replace sentinel placeholder with actual action script content
$deployerFinal = $deployerTemplate.Replace('##EMBEDDED_ACTION_SCRIPT##', $actionScriptContent.TrimEnd())

Set-Content -Path $deployerOutput -Value $deployerFinal -Encoding UTF8 -Force
Write-Host "Build complete: $deployerOutput"
